[[OpenBLAS]]
arch = "i686"
git-tree-sha1 = "cc73a31f48ae25d59e754d97e91396645c670324"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "6ee0ad5a9fbba6839af48ca67cccc9a247565ce6c41ebfb23fda18b0142c94b5"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "x86_64"
git-tree-sha1 = "25a5620b07f0adb58ce255f90833a615f8b8178c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "43b2e6897b29450dc844fa4223eb3ae0258e2aa8ff1eadccf9b06d67b45c5137"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "aarch64"
git-tree-sha1 = "3e95a98e5866834fc57be32283052ff950c9b8fb"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "a2e040eff8c1afadea3b4f4a029d1d0a009fb48eeca06d810527b3b6b5a6622e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7ea3c3edb0bc335cf544c477f83eb690e230a092"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "ef440c14860a5c8c2ff7ec87cde1741a199d5279d14daa6733ab0821f0fc6383"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7ea3c3edb0bc335cf544c477f83eb690e230a092"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "ef440c14860a5c8c2ff7ec87cde1741a199d5279d14daa6733ab0821f0fc6383"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "powerpc64le"
git-tree-sha1 = "f7ea4678ef18a224c9dff5170333b4576a6ebd01"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "ba56390d0b4500f19c04d01d476b4699081d0a9d3d85bb380d7fa679bcd99962"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "riscv64"
git-tree-sha1 = "4aab237d2984b5e8eb74711a07d0668ac1cbaaff"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "21dbbc4928a31919fe58c94246a337aa3b2a0278053a0e461b7e7c8003465d7b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.riscv64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "i686"
git-tree-sha1 = "9ff536f9bc0b74c7a742c33ff5481110aef2d9d2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "98fd46a92046aec3de6ff0f8ca8c2f964827727e24fc895664e44141a64c1baa"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "x86_64"
git-tree-sha1 = "5a07b043a375c4406f027e871f7d368db4f8987e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "4f337e8898cb2cb8d11b210c465eaaabbc208219e0f5a6ff8afaf8ad2a1bcbfa"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "aarch64"
git-tree-sha1 = "b49ff62c73d052d6702b356ef44a7ed599cec920"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "e83eac189c4fb27b6c3fdad832e1e1f120cccc69fc377a037209535900767f20"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "11f445317d46f2e8a35f3fb4b52afef1fe330d62"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "41588b25ed082bffe4245b31643160347f2c6a11d2deb0311095f6068d1d1860"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "11f445317d46f2e8a35f3fb4b52afef1fe330d62"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "41588b25ed082bffe4245b31643160347f2c6a11d2deb0311095f6068d1d1860"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "x86_64"
git-tree-sha1 = "9903468eccf69c0a9c3dc12e743953cd5fe3e5e1"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS.download]]
    sha256 = "20d4ce50a602d8c41c94be6badf04d1091bda0300730d1c19ac4958e03daa537"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "aarch64"
git-tree-sha1 = "7fa712efb41cf22ca2c55c9b5b2a98bdca454878"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS.download]]
    sha256 = "c78d51a6d8dd2cc7b553dcb49a7663dfef4fb268888556877f74a473a4304e52"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "x86_64"
git-tree-sha1 = "aa5820760cb95adcc8fa3be2107af68fd91a8878"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS.download]]
    sha256 = "4355b2b6aeeeae90a8c78f1dd761de72945aad82f147fc81826c352096831304"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "aarch64"
git-tree-sha1 = "0fc11df73d140e8bc474c519408dc3c6a6664d0e"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS.download]]
    sha256 = "3460dfdb9fea9f61fbb1af8350fa5a7bd7b56fb44ca1cd43cb31318a97f1228c"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "i686"
git-tree-sha1 = "327b70ab2e5b8e0c4292482e0e2deaaa85c875f5"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS.download]]
    sha256 = "b7c0ad24d396b2a77ae4a83ba0f544f3bdedb05586a71f0725b2f1b0026e08da"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "x86_64"
git-tree-sha1 = "e98840d819f103a57c5fb15289d4c910efc9dfb9"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS.download]]
    sha256 = "56b943c12f09bfa877c092d2972e076a2d5bbe8af9e6d46a92a2111f3fe6d87e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "x86_64"
git-tree-sha1 = "07c43ee58d03698fd4fe318ac6c6e28eba583541"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[OpenBLAS.download]]
    sha256 = "4ab0d8f5e950ff57b49e6f4c1512b75a93737a89519b36c3818905b02a44bdbd"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+1/OpenBLAS.v0.3.33.x86_64-linux-gnu-sanitize+memory.tar.gz"
