[[OpenBLAS]]
arch = "i686"
git-tree-sha1 = "b939ac264fd31308f3112788fc8dc7acb561a716"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "f45468cbb31039ec9559c2a417210826f0c5c5c282bd4bd7dc50f4aa6bbd9a4d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "x86_64"
git-tree-sha1 = "65b4f43e9fb4368bc4dafadfacb0bf0759bcb3a0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "cc1033cae231c1f3ebb481efb5a4a81e78f74b30dbf0ca046f7cdadfae3efd95"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "aarch64"
git-tree-sha1 = "1d16774e5597e49445665b07c66c6d8391bc98f6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "a560491c57de1a9adb5e0d1662906f2bd74b5077065694acdf4c34c983092792"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d474c49b756ad1ae1f8d462f281afdbd3590338f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "943311e33a866c5cfddd2f4696cb7ae17c58cb1e6fba05e9a19c44019cb841ef"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d474c49b756ad1ae1f8d462f281afdbd3590338f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "943311e33a866c5cfddd2f4696cb7ae17c58cb1e6fba05e9a19c44019cb841ef"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "powerpc64le"
git-tree-sha1 = "34a2639553ce443e95a1be7647a4d0f007d160d6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "2e1afb4133ed9e201867a5bcdd5852906487ab83ae42fa2a73cfa8c80885fbee"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "riscv64"
git-tree-sha1 = "93bc9eefb9c12d0d0acf862a9adffff2b4368136"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "685acfc91458abdd83a6ecb8a3b264a4b0438ca703f20125b88f6e386d7c09ad"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.riscv64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "i686"
git-tree-sha1 = "daed13099f12d16822025c2c803a05fc0991b329"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "be65c7f0f094777cc36bccafa24d72d562f825f2e0d896901ffeac3e5521af73"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "x86_64"
git-tree-sha1 = "a1a35994d3ae4820d38e1a74422ac6d93e7ec54a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "77907f9cd38f973b41a3672742f8bee08252b2c681a18bab6a61474b055c1e7e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "aarch64"
git-tree-sha1 = "f24faccd6d0f50ec46e9d45c3863cdcc0396447a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "296edb5cc2222ac0395f6a5e8bc73ac64d7a885eec8febe963c5ad3d3cad9054"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fef2bc4f19461b8346a603ee6916b8ba8cf7822f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "608ad80890d061de788a075dacdf6693792613bcca781a530ada0aac75988ca8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fef2bc4f19461b8346a603ee6916b8ba8cf7822f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "608ad80890d061de788a075dacdf6693792613bcca781a530ada0aac75988ca8"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "x86_64"
git-tree-sha1 = "207da9a0a965372a145dba9cbec624e0501a49f3"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS.download]]
    sha256 = "766c5d1e57389582b318436dfe0a6d25faf22320d8c83c97755ed15a5d87fc29"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "aarch64"
git-tree-sha1 = "81dba563e05f3381a33b96c8197e51d7c7eecf0b"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS.download]]
    sha256 = "1295518f1efadfa800467fafb7fd733d0a930d572f3940801f33ca14b3965d33"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "x86_64"
git-tree-sha1 = "1e32808875da97b136974c63a5d2c01828cb4bbc"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS.download]]
    sha256 = "06016e13d20779a02865d7425c6c69b32655e376a1e3041091e43534a9ca81de"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "aarch64"
git-tree-sha1 = "bfac6b12a0abc4eff159fc005e44e70a4662caac"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS.download]]
    sha256 = "03105f8d242bb222aa8ac2ad866c41fe6bf2515a29ffdf4e8411d2c5e804ac7d"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "i686"
git-tree-sha1 = "7caf8506473c5fa3cdd22ad42917d4091f1ac315"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS.download]]
    sha256 = "f14a85f8c58dac8e62fd8e65774f93b5caac000ef30804f19077025193ae3c0e"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "x86_64"
git-tree-sha1 = "416cc91f3fa843bd3b2688b2b834b5280e8dd72d"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS.download]]
    sha256 = "12e745540d62fdd79078938e65dbc1199b2775da5fa2f6f19419a50361b9b888"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "x86_64"
git-tree-sha1 = "50faaad9042417cef33d07931e617e7af9f9e795"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[OpenBLAS.download]]
    sha256 = "50592d16e83eff513c2bdb1f517fc618a8e948c024bda2f9e0a06465154ffce6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.33+0/OpenBLAS.v0.3.33.x86_64-linux-gnu-sanitize+memory.tar.gz"
