[[OpenBLAS]]
arch = "aarch64"
git-tree-sha1 = "f52d291d44557fd3413b71e9d396cadc1c737aa3"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS.download]]
    sha256 = "8eea6b98ee0e477e441028656f07fa668eb69addc54eb2751319087554c878a2"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.aarch64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "aarch64"
git-tree-sha1 = "59682c66d6158e87bab963d23a8f2e44a1626987"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "7ee148d0cc14c62402f68286a1ed2732d42278aa9b651341c9fb6a2115ad7626"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.aarch64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "aarch64"
git-tree-sha1 = "f1ef54777d3f21b18a923ddd0b4dc42877937476"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "39f8632770bdcced3e18d9ae3689a26b93b5637098583c0eec7f41695a4e8355"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.aarch64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "aarch64"
git-tree-sha1 = "1d51ea45e46c8bf3b4fa0d332d9f80a6d4f1ff29"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS.download]]
    sha256 = "f3786052efc27e1a4118246ab46fb4e9ccb2b344c7af7d50e53df32edb90e12f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "af5fc844107fbac51bf55fd508af7c01e91564b4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "fb6faf4334c697760e452b35cd1e3b0f453005fa4b6007ca60ffb02e8037c9d1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e121178d31c1ccf2af5bbdd495fbd94f8b5c7b28"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "4f858c39728430708c9b28ea7737ba3e7aeb274f8d240d3287f21ab488de222f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "af5fc844107fbac51bf55fd508af7c01e91564b4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "fb6faf4334c697760e452b35cd1e3b0f453005fa4b6007ca60ffb02e8037c9d1"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e121178d31c1ccf2af5bbdd495fbd94f8b5c7b28"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "4f858c39728430708c9b28ea7737ba3e7aeb274f8d240d3287f21ab488de222f"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "i686"
git-tree-sha1 = "6fbcde9654a5889bcf7d76ae51b542348c1434b2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "d6b48ca1bc140c67b4d857a4b05b31dcad6a4f2c2063027199c9b7a3c4fa0213"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.i686-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "i686"
git-tree-sha1 = "26530fd8ee9a931051b1b2e68fba42368070b35e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "423f2fcb69c416ad7a4116211676955d5ef7a5b741f8f58731d1e7795f237410"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.i686-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "i686"
git-tree-sha1 = "aca0db3d04e67cd13e41c89ffb5a29231ebf619f"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS.download]]
    sha256 = "a7bd400ff5f18021a7927a995079c97400cf75d92d5fa4e4d4e292b8a46521e4"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.i686-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "powerpc64le"
git-tree-sha1 = "8c63dac58e9a2edf5df0cc683668c621da712615"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "b5f24dcefcb676c22d20a0dc4df871c8fc4951e082b117375e9c98d58a28712b"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "riscv64"
git-tree-sha1 = "cb416dfc5b3c27f37caff86da79982a1604713e6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "d6370c58ff8d87d1905c108f6a6b5b87d99507feb6e7f138b41299f7ad1cd6c0"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.riscv64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "x86_64"
git-tree-sha1 = "dfb93c49b7bc0e26daa8ac15746cc3afcc78fca3"
libgfortran_version = "5.0.0"
os = "macos"

    [[OpenBLAS.download]]
    sha256 = "f6a791e707956b785f08a162a252f75c75abdb23c03d6832946919fe4f7b7e66"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.x86_64-apple-darwin-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "x86_64"
git-tree-sha1 = "b37e423d368f5529bb74667f43c3ce9aae94c495"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "66bea625eceac84062d46f64777149a3d594a9436e91e12f80920e5cafd14aa6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.x86_64-linux-gnu-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "x86_64"
git-tree-sha1 = "8dc58eea4793ba17c1a8f5008a7a81416e1007de"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[OpenBLAS.download]]
    sha256 = "302d5fdf2af40ece3f13601929cf59f9f510e6a4e3c80c9e734513932dfcf8e6"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.x86_64-linux-musl-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "x86_64"
git-tree-sha1 = "e754aff7444aaa19702e71dc01d8bcc81606aea6"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[OpenBLAS.download]]
    sha256 = "55d6cc61dd7aea3509b621d656ed719240148ac0649c4b09392d86161967d246"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "x86_64"
git-tree-sha1 = "ba30999b77eb1fd59daefe0b07e7cc0f77351521"
libgfortran_version = "5.0.0"
os = "windows"

    [[OpenBLAS.download]]
    sha256 = "cce478c381312ed0bc67e2537a57944656d224eb7286c5512e6f31c71bb9e735"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[OpenBLAS]]
arch = "x86_64"
git-tree-sha1 = "8943276821117d4e1e5f356633e03777f42c2258"
libc = "glibc"
os = "linux"
sanitize = "memory"

    [[OpenBLAS.download]]
    sha256 = "ccffb0ae8265e8c3f003d831de236287e588f52c6c3565da32e8123dd49d3771"
    url = "https://github.com/JuliaBinaryWrappers/OpenBLAS_jll.jl/releases/download/OpenBLAS-v0.3.30+0/OpenBLAS.v0.3.30.x86_64-linux-gnu-sanitize+memory.tar.gz"
